from django.db import models
from django.contrib.gis.db import models

# Create your models here.
class conflict_data(models.Model):
    event_id_cnty = models.CharField(null=True, blank=True)
    event_date = models.CharField(null=True, blank=True)
    year = models.FloatField(null=True, blank=True)
    time_precision = models.FloatField(null=True, blank=True)
    disorder_type = models.CharField(null=True, blank=True)
    event_type = models.CharField(null=True, blank=True)
    sub_event_type = models.CharField(null=True, blank=True)
    actor1 = models.CharField(null=True, blank=True)
    assoc_actor_1 = models.CharField(null=True, blank=True)
    inter1 = models.CharField(null=True, blank=True)
    actor2 = models.CharField(null=True, blank=True)
    assoc_actor_2 = models.CharField(null=True, blank=True)
    inter2 = models.CharField(null=True, blank=True)
    interaction = models.CharField(null=True, blank=True)
    civilian_targeting = models.CharField(null=True, blank=True)
    iso = models.FloatField(null=True, blank=True)
    region = models.CharField(null=True, blank=True)
    country = models.CharField(null=True, blank=True)
    admin1 = models.CharField(null=True, blank=True)
    admin2 = models.CharField(null=True, blank=True)
    admin3 = models.CharField(null=True, blank=True)
    location = models.CharField(null=True, blank=True)
    geo_precision = models.FloatField(null=True, blank=True)
    source = models.CharField(null=True, blank=True)
    source_scale = models.CharField(null=True, blank=True)
    notes = models.CharField(null=True, blank=True)
    fatalities = models.FloatField(null=True, blank=True)
    tags = models.CharField(null=True, blank=True)
    timestamp = models.FloatField(null=True, blank=True)
    geom = models.MultiPointField(srid=4326)