# Generated by Django 4.2 on 2025-05-14 11:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conflict_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id_cnty', models.CharField(unique=True)),
                ('event_date', models.CharField()),
                ('year', models.FloatField()),
                ('time_precision', models.FloatField()),
                ('disorder_type', models.CharField()),
                ('event_type', models.CharField()),
                ('sub_event_type', models.CharField()),
                ('actor1', models.CharField()),
                ('assoc_actor_1', models.CharField()),
                ('inter1', models.CharField()),
                ('actor2', models.CharField()),
                ('assoc_actor_2', models.CharField()),
                ('inter2', models.CharField()),
                ('interaction', models.CharField()),
                ('civilian_targeting', models.CharField()),
                ('iso', models.FloatField()),
                ('region', models.CharField()),
                ('country', models.CharField()),
                ('admin1', models.CharField()),
                ('admin2', models.CharField()),
                ('admin3', models.CharField()),
                ('location', models.CharField()),
                ('geo_precision', models.FloatField()),
                ('source', models.CharField()),
                ('source_scale', models.CharField()),
                ('notes', models.CharField()),
                ('fatalities', models.FloatField()),
                ('tags', models.CharField()),
                ('timestamp', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
