# Generated by Django 4.2 on 2025-05-15 17:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conflict_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id_cnty', models.CharField(blank=True, null=True)),
                ('event_date', models.CharField(blank=True, null=True)),
                ('year', models.FloatField(blank=True, null=True)),
                ('time_precision', models.FloatField(blank=True, null=True)),
                ('disorder_type', models.CharField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, null=True)),
                ('sub_event_type', models.CharField(blank=True, null=True)),
                ('actor1', models.CharField(blank=True, null=True)),
                ('assoc_actor_1', models.CharField(blank=True, null=True)),
                ('inter1', models.CharField(blank=True, null=True)),
                ('actor2', models.CharField(blank=True, null=True)),
                ('assoc_actor_2', models.CharField(blank=True, null=True)),
                ('inter2', models.CharField(blank=True, null=True)),
                ('interaction', models.CharField(blank=True, null=True)),
                ('civilian_targeting', models.CharField(blank=True, null=True)),
                ('iso', models.FloatField(blank=True, null=True)),
                ('region', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('admin1', models.CharField(blank=True, null=True)),
                ('admin2', models.CharField(blank=True, null=True)),
                ('admin3', models.CharField(blank=True, null=True)),
                ('location', models.CharField(blank=True, null=True)),
                ('geo_precision', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, null=True)),
                ('source_scale', models.CharField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, null=True)),
                ('fatalities', models.FloatField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, null=True)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ssd_level_0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ssd_level_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_1', models.CharField(blank=True, null=True)),
                ('gid_0', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('state', models.CharField(blank=True, null=True)),
                ('varname_1', models.CharField(blank=True, null=True)),
                ('nl_name_1', models.CharField(blank=True, null=True)),
                ('type_1', models.CharField(blank=True, null=True)),
                ('engtype_1', models.CharField(blank=True, null=True)),
                ('cc_1', models.CharField(blank=True, null=True)),
                ('hasc_1', models.CharField(blank=True, null=True)),
                ('iso_code', models.CharField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
