# Generated by Django 4.2 on 2025-05-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict_data',
            name='civilian_targeting',
            field=models.CharField(blank=True, null=True),
        ),
    ]
