# Generated by Django 4.2 on 2025-05-15 17:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssd_level_1',
            old_name='iso_code',
            new_name='iso_1',
        ),
        migrations.RenameField(
            model_name='ssd_level_1',
            old_name='state',
            new_name='name_1',
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='ssd_level_0',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='ssd_level_1',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
