# Generated by Django 4.2 on 2025-05-15 10:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0002_ssd_level_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='ssd_level_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_1', models.CharField(blank=True, null=True)),
                ('gid_0', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('name_1', models.CharField(blank=True, null=True)),
                ('varname_1', models.CharField(blank=True, null=True)),
                ('nl_name_1', models.CharField(blank=True, null=True)),
                ('type_1', models.CharField(blank=True, null=True)),
                ('engtype_1', models.CharField(blank=True, null=True)),
                ('cc_1', models.CharField(blank=True, null=True)),
                ('hasc_1', models.CharField(blank=True, null=True)),
                ('iso_1', models.CharField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
