# Generated by Django 4.2 on 2025-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0003_alter_conflict_data_civilian_targeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict_data',
            name='event_id_cnty',
            field=models.CharField(),
        ),
    ]
