# Generated by Django 4.2 on 2025-05-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0003_ssd_level_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssd_level_1',
            old_name='name_1',
            new_name='state',
        ),
    ]
