# Generated by Django 4.2 on 2025-05-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0004_rename_name_1_ssd_level_1_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssd_level_1',
            old_name='state',
            new_name='name_1',
        ),
    ]
