# Generated by Django 4.2 on 2025-05-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0004_alter_conflict_data_event_id_cnty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict_data',
            name='actor1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='actor2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='admin1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='admin2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='admin3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='assoc_actor_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='assoc_actor_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='civilian_targeting',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='disorder_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='event_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='event_id_cnty',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='event_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='fatalities',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='geo_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='inter1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='inter2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='interaction',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='iso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='notes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='region',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='source',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='source_scale',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='sub_event_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='tags',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='time_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conflict_data',
            name='year',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
