# Generated by Django 4.2 on 2025-05-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0005_rename_state_ssd_level_1_name_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssd_level_1',
            old_name='iso_1',
            new_name='iso_code',
        ),
        migrations.RenameField(
            model_name='ssd_level_1',
            old_name='name_1',
            new_name='state',
        ),
    ]
